theme: jekyll-theme-cayman
title: Holden Sparacino
description: Portfolio and blog

twitter_username: holdensparacino
instagram_username: holdensparacino

disqus:
  shortname: holdensparacino
  
google_analytics: UA-71628943-4


header_pages:
  - about.md
  - portfolio.md
